### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by dutran** [SunghwanHong/Cost-Aggregation-transformers#9]
Hi [Sunghwan Hong](https://github.com/SunghwanHong),
Thanks for sharing the code. I have one question:

Will this be a potential bug at line https://github.com/SunghwanHong/Cost-Aggregation-transformers/blob/main/utils_training/evaluation.py#L32?

Should it be 'trg_kps' instead of src_kps?

Thanks

**Comment by SunghwanHong** [comment]
Hello, 
Thanks for your interest in our work.

I guess, issue #5 is closely related to your question. I believe since we use source and target images in a reverse manner compared to DHPF or CHM, this resulted some confusions. As #5 says, we project target keypoints to source, which is why it is written as src_kps. This may lead to different results compared to when we were to project source keypoint to target.

**Comment by dutran** [comment]
Thanks for the clarification!
